// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Test_SuaBP
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_SuaBP - Use 'RecordedMethod_SuaBPParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_SuaBP()
        {
            #region Variable Declarations
            WinButton uIEDITButton = this.UIHomeWindow.UIEDITWindow.UIEDITButton;
            WinEdit uITxtTenBPEdit = this.UIHomeWindow.UITxtTenBPWindow.UITxtTenBPEdit;
            WinButton uISAVEButton = this.UIHomeWindow.UISAVEWindow.UISAVEButton;
            #endregion

            // Click 'EDIT' button
            Mouse.Click(uIEDITButton, new Point(132, 73));

            // Type 'Nhân Viên Giao Hàng' in 'txtTenBP' text box
            uITxtTenBPEdit.Text = this.RecordedMethod_SuaBPParams.UITxtTenBPEditText;

            // Click 'SAVE' button
            Mouse.Click(uISAVEButton, new Point(178, 54));
        }
        
        /// <summary>
        /// AssertMethod1_SuaTC - Use 'AssertMethod1_SuaTCExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1_SuaTC()
        {
            #region Variable Declarations
            WinText uISửathànhcôngText = this.UIMessageBoxThanhCongWindow.UISửathànhcôngWindow.UISửathànhcôngText;
            #endregion

            // Verify that the 'Name' property of 'Sửa thành công.' label equals 'Sửa thành công.'
            Assert.AreEqual(this.AssertMethod1_SuaTCExpectedValues.UISửathànhcôngTextName, uISửathànhcôngText.Name);
        }
        
        /// <summary>
        /// AssertMethod_NullTenBP - Use 'AssertMethod_NullTenBPExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_NullTenBP()
        {
            #region Variable Declarations
            WinText uIHãyđiềndữliệuđầyđủText = this.UIMessageBoxCustomWindow.UIHãyđiềndữliệuđầyđủWindow.UIHãyđiềndữliệuđầyđủText;
            #endregion

            // Verify that the 'Name' property of 'Hãy điền dữ liệu đầy đủ' label equals 'Hãy điền dữ liệu đầy đủ'
            Assert.AreEqual(this.AssertMethod_NullTenBPExpectedValues.UIHãyđiềndữliệuđầyđủTextName, uIHãyđiềndữliệuđầyđủText.Name);
        }
        
        /// <summary>
        /// AssertMethod_TenBPDaTonTai - Use 'AssertMethod_TenBPDaTonTaiExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_TenBPDaTonTai()
        {
            #region Variable Declarations
            WinText uITênbộphậnđãtồntạiText = this.UIMessageBoxCustomWindow.UIHãyđiềndữliệuđầyđủWindow.UITênbộphậnđãtồntạiText;
            #endregion

            // Verify that the 'Name' property of 'Tên bộ phận đã tồn tại.' label equals 'Tên bộ phận đã tồn tại.'
            Assert.AreEqual(this.AssertMethod_TenBPDaTonTaiExpectedValues.UITênbộphậnđãtồntạiTextName, uITênbộphậnđãtồntạiText.Name);
        }
        
        #region Properties
        public virtual RecordedMethod_SuaBPParams RecordedMethod_SuaBPParams
        {
            get
            {
                if ((this.mRecordedMethod_SuaBPParams == null))
                {
                    this.mRecordedMethod_SuaBPParams = new RecordedMethod_SuaBPParams();
                }
                return this.mRecordedMethod_SuaBPParams;
            }
        }
        
        public virtual AssertMethod1_SuaTCExpectedValues AssertMethod1_SuaTCExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1_SuaTCExpectedValues == null))
                {
                    this.mAssertMethod1_SuaTCExpectedValues = new AssertMethod1_SuaTCExpectedValues();
                }
                return this.mAssertMethod1_SuaTCExpectedValues;
            }
        }
        
        public virtual AssertMethod_NullTenBPExpectedValues AssertMethod_NullTenBPExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_NullTenBPExpectedValues == null))
                {
                    this.mAssertMethod_NullTenBPExpectedValues = new AssertMethod_NullTenBPExpectedValues();
                }
                return this.mAssertMethod_NullTenBPExpectedValues;
            }
        }
        
        public virtual AssertMethod_TenBPDaTonTaiExpectedValues AssertMethod_TenBPDaTonTaiExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_TenBPDaTonTaiExpectedValues == null))
                {
                    this.mAssertMethod_TenBPDaTonTaiExpectedValues = new AssertMethod_TenBPDaTonTaiExpectedValues();
                }
                return this.mAssertMethod_TenBPDaTonTaiExpectedValues;
            }
        }
        
        public UIHomeWindow UIHomeWindow
        {
            get
            {
                if ((this.mUIHomeWindow == null))
                {
                    this.mUIHomeWindow = new UIHomeWindow();
                }
                return this.mUIHomeWindow;
            }
        }
        
        public UIMessageBoxThanhCongWindow UIMessageBoxThanhCongWindow
        {
            get
            {
                if ((this.mUIMessageBoxThanhCongWindow == null))
                {
                    this.mUIMessageBoxThanhCongWindow = new UIMessageBoxThanhCongWindow();
                }
                return this.mUIMessageBoxThanhCongWindow;
            }
        }
        
        public UIMessageBoxCustomWindow UIMessageBoxCustomWindow
        {
            get
            {
                if ((this.mUIMessageBoxCustomWindow == null))
                {
                    this.mUIMessageBoxCustomWindow = new UIMessageBoxCustomWindow();
                }
                return this.mUIMessageBoxCustomWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod_SuaBPParams mRecordedMethod_SuaBPParams;
        
        private AssertMethod1_SuaTCExpectedValues mAssertMethod1_SuaTCExpectedValues;
        
        private AssertMethod_NullTenBPExpectedValues mAssertMethod_NullTenBPExpectedValues;
        
        private AssertMethod_TenBPDaTonTaiExpectedValues mAssertMethod_TenBPDaTonTaiExpectedValues;
        
        private UIHomeWindow mUIHomeWindow;
        
        private UIMessageBoxThanhCongWindow mUIMessageBoxThanhCongWindow;
        
        private UIMessageBoxCustomWindow mUIMessageBoxCustomWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_SuaBP'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod_SuaBPParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Nhân Viên Giao Hàng' in 'txtTenBP' text box
        /// </summary>
        public string UITxtTenBPEditText = "Nhân Viên Giao Hàng";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1_SuaTC'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AssertMethod1_SuaTCExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Sửa thành công.' label equals 'Sửa thành công.'
        /// </summary>
        public string UISửathànhcôngTextName = "Sửa thành công.";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_NullTenBP'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AssertMethod_NullTenBPExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Hãy điền dữ liệu đầy đủ' label equals 'Hãy điền dữ liệu đầy đủ'
        /// </summary>
        public string UIHãyđiềndữliệuđầyđủTextName = "Hãy điền dữ liệu đầy đủ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_TenBPDaTonTai'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AssertMethod_TenBPDaTonTaiExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Tên bộ phận đã tồn tại.' label equals 'Tên bộ phận đã tồn tại.'
        /// </summary>
        public string UITênbộphậnđãtồntạiTextName = "Tên bộ phận đã tồn tại.";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomeWindow : WinWindow
    {
        
        public UIHomeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Home";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public UIEDITWindow UIEDITWindow
        {
            get
            {
                if ((this.mUIEDITWindow == null))
                {
                    this.mUIEDITWindow = new UIEDITWindow(this);
                }
                return this.mUIEDITWindow;
            }
        }
        
        public UITxtTenBPWindow UITxtTenBPWindow
        {
            get
            {
                if ((this.mUITxtTenBPWindow == null))
                {
                    this.mUITxtTenBPWindow = new UITxtTenBPWindow(this);
                }
                return this.mUITxtTenBPWindow;
            }
        }
        
        public UISAVEWindow UISAVEWindow
        {
            get
            {
                if ((this.mUISAVEWindow == null))
                {
                    this.mUISAVEWindow = new UISAVEWindow(this);
                }
                return this.mUISAVEWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEDITWindow mUIEDITWindow;
        
        private UITxtTenBPWindow mUITxtTenBPWindow;
        
        private UISAVEWindow mUISAVEWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIEDITWindow : WinWindow
    {
        
        public UIEDITWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "mnusua";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinButton UIEDITButton
        {
            get
            {
                if ((this.mUIEDITButton == null))
                {
                    this.mUIEDITButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIEDITButton.SearchProperties[WinButton.PropertyNames.Name] = "EDIT";
                    this.mUIEDITButton.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUIEDITButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIEDITButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITxtTenBPWindow : WinWindow
    {
        
        public UITxtTenBPWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTenBP";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTenBPEdit
        {
            get
            {
                if ((this.mUITxtTenBPEdit == null))
                {
                    this.mUITxtTenBPEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTenBPEdit.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUITxtTenBPEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTenBPEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISAVEWindow : WinWindow
    {
        
        public UISAVEWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "mnuluu";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinButton UISAVEButton
        {
            get
            {
                if ((this.mUISAVEButton == null))
                {
                    this.mUISAVEButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISAVEButton.SearchProperties[WinButton.PropertyNames.Name] = "SAVE";
                    this.mUISAVEButton.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUISAVEButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISAVEButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMessageBoxThanhCongWindow : WinWindow
    {
        
        public UIMessageBoxThanhCongWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MessageBoxThanhCong";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MessageBoxThanhCong");
            #endregion
        }
        
        #region Properties
        public UISửathànhcôngWindow UISửathànhcôngWindow
        {
            get
            {
                if ((this.mUISửathànhcôngWindow == null))
                {
                    this.mUISửathànhcôngWindow = new UISửathànhcôngWindow(this);
                }
                return this.mUISửathànhcôngWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISửathànhcôngWindow mUISửathànhcôngWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISửathànhcôngWindow : WinWindow
    {
        
        public UISửathànhcôngWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Test";
            this.WindowTitles.Add("MessageBoxThanhCong");
            #endregion
        }
        
        #region Properties
        public WinText UISửathànhcôngText
        {
            get
            {
                if ((this.mUISửathànhcôngText == null))
                {
                    this.mUISửathànhcôngText = new WinText(this);
                    #region Search Criteria
                    this.mUISửathànhcôngText.SearchProperties[WinText.PropertyNames.Name] = "Sửa thành công.";
                    this.mUISửathànhcôngText.WindowTitles.Add("MessageBoxThanhCong");
                    #endregion
                }
                return this.mUISửathànhcôngText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUISửathànhcôngText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMessageBoxCustomWindow : WinWindow
    {
        
        public UIMessageBoxCustomWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MessageBoxCustom";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MessageBoxCustom");
            #endregion
        }
        
        #region Properties
        public UIHãyđiềndữliệuđầyđủWindow UIHãyđiềndữliệuđầyđủWindow
        {
            get
            {
                if ((this.mUIHãyđiềndữliệuđầyđủWindow == null))
                {
                    this.mUIHãyđiềndữliệuđầyđủWindow = new UIHãyđiềndữliệuđầyđủWindow(this);
                }
                return this.mUIHãyđiềndữliệuđầyđủWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHãyđiềndữliệuđầyđủWindow mUIHãyđiềndữliệuđầyđủWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHãyđiềndữliệuđầyđủWindow : WinWindow
    {
        
        public UIHãyđiềndữliệuđầyđủWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Test";
            this.WindowTitles.Add("MessageBoxCustom");
            #endregion
        }
        
        #region Properties
        public WinText UIHãyđiềndữliệuđầyđủText
        {
            get
            {
                if ((this.mUIHãyđiềndữliệuđầyđủText == null))
                {
                    this.mUIHãyđiềndữliệuđầyđủText = new WinText(this);
                    #region Search Criteria
                    this.mUIHãyđiềndữliệuđầyđủText.SearchProperties[WinText.PropertyNames.Name] = "Hãy điền dữ liệu đầy đủ";
                    this.mUIHãyđiềndữliệuđầyđủText.WindowTitles.Add("MessageBoxCustom");
                    #endregion
                }
                return this.mUIHãyđiềndữliệuđầyđủText;
            }
        }
        
        public WinText UITênbộphậnđãtồntạiText
        {
            get
            {
                if ((this.mUITênbộphậnđãtồntạiText == null))
                {
                    this.mUITênbộphậnđãtồntạiText = new WinText(this);
                    #region Search Criteria
                    this.mUITênbộphậnđãtồntạiText.SearchProperties[WinText.PropertyNames.Name] = "Tên bộ phận đã tồn tại.";
                    this.mUITênbộphậnđãtồntạiText.WindowTitles.Add("MessageBoxCustom");
                    #endregion
                }
                return this.mUITênbộphậnđãtồntạiText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIHãyđiềndữliệuđầyđủText;
        
        private WinText mUITênbộphậnđãtồntạiText;
        #endregion
    }
}
