// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Test_XoaBP
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test_XoaBoPhan
        /// </summary>
        public void Test_XoaBoPhan()
        {
            #region Variable Declarations
            WinCell uIBP05Cell = this.UIHomeWindow.UIDgvBoPhanWindow.UIDataGridViewTable.UIRow0Row1.UIBP05Cell;
            WinButton uIREMOVEButton = this.UIHomeWindow.UIREMOVEWindow.UIREMOVEButton;
            #endregion

            // Click 'BP05' cell
            Mouse.Click(uIBP05Cell, new Point(310, 20));

            // Click 'REMOVE' button
            Mouse.Click(uIREMOVEButton, new Point(145, 66));
        }
        
        /// <summary>
        /// Test_XoaBoPhan1
        /// </summary>
        public void Test_XoaBoPhan1()
        {
            #region Variable Declarations
            WinCell uIBP02Cell = this.UIHomeWindow.UIDgvBoPhanWindow.UIDataGridViewTable.UIRow1Row.UIBP02Cell;
            WinButton uIREMOVEButton = this.UIHomeWindow.UIREMOVEWindow.UIREMOVEButton;
            #endregion

            // Click 'BP02' cell
            Mouse.Click(uIBP02Cell, new Point(709, 19));

            // Click 'REMOVE' button
            Mouse.Click(uIREMOVEButton, new Point(122, 69));
        }
        
        /// <summary>
        /// Assert_KhongXoaDuoc - Use 'Assert_KhongXoaDuocExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert_KhongXoaDuoc()
        {
            #region Variable Declarations
            WinText uIKhôngthểxóađượcText = this.UIMessageBoxCustomWindow.UIKhôngthểxóađượcWindow.UIKhôngthểxóađượcText;
            #endregion

            // Verify that the 'Name' property of 'Không thể xóa được.' label equals 'Không thể xóa được.'
            Assert.AreEqual(this.Assert_KhongXoaDuocExpectedValues.UIKhôngthểxóađượcTextName, uIKhôngthểxóađượcText.Name);
        }
        
        /// <summary>
        /// Assert_XoaThanhCong - Use 'Assert_XoaThanhCongExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert_XoaThanhCong()
        {
            #region Variable Declarations
            WinText uIXóathànhcôngText = this.UIMessageBoxThanhCongWindow.UIXóathànhcôngWindow.UIXóathànhcôngText;
            #endregion

            // Verify that the 'Name' property of 'Xóa thành công.' label equals 'Xóa thành công.'
            Assert.AreEqual(this.Assert_XoaThanhCongExpectedValues.UIXóathànhcôngTextName, uIXóathànhcôngText.Name);
        }
        
        #region Properties
        public virtual Assert_KhongXoaDuocExpectedValues Assert_KhongXoaDuocExpectedValues
        {
            get
            {
                if ((this.mAssert_KhongXoaDuocExpectedValues == null))
                {
                    this.mAssert_KhongXoaDuocExpectedValues = new Assert_KhongXoaDuocExpectedValues();
                }
                return this.mAssert_KhongXoaDuocExpectedValues;
            }
        }
        
        public virtual Assert_XoaThanhCongExpectedValues Assert_XoaThanhCongExpectedValues
        {
            get
            {
                if ((this.mAssert_XoaThanhCongExpectedValues == null))
                {
                    this.mAssert_XoaThanhCongExpectedValues = new Assert_XoaThanhCongExpectedValues();
                }
                return this.mAssert_XoaThanhCongExpectedValues;
            }
        }
        
        public UIHomeWindow UIHomeWindow
        {
            get
            {
                if ((this.mUIHomeWindow == null))
                {
                    this.mUIHomeWindow = new UIHomeWindow();
                }
                return this.mUIHomeWindow;
            }
        }
        
        public UIMessageBoxThanhCongWindow UIMessageBoxThanhCongWindow
        {
            get
            {
                if ((this.mUIMessageBoxThanhCongWindow == null))
                {
                    this.mUIMessageBoxThanhCongWindow = new UIMessageBoxThanhCongWindow();
                }
                return this.mUIMessageBoxThanhCongWindow;
            }
        }
        
        public UIMessageBoxCustomWindow UIMessageBoxCustomWindow
        {
            get
            {
                if ((this.mUIMessageBoxCustomWindow == null))
                {
                    this.mUIMessageBoxCustomWindow = new UIMessageBoxCustomWindow();
                }
                return this.mUIMessageBoxCustomWindow;
            }
        }
        #endregion
        
        #region Fields
        private Assert_KhongXoaDuocExpectedValues mAssert_KhongXoaDuocExpectedValues;
        
        private Assert_XoaThanhCongExpectedValues mAssert_XoaThanhCongExpectedValues;
        
        private UIHomeWindow mUIHomeWindow;
        
        private UIMessageBoxThanhCongWindow mUIMessageBoxThanhCongWindow;
        
        private UIMessageBoxCustomWindow mUIMessageBoxCustomWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert_KhongXoaDuoc'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Assert_KhongXoaDuocExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Không thể xóa được.' label equals 'Không thể xóa được.'
        /// </summary>
        public string UIKhôngthểxóađượcTextName = "Không thể xóa được.";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert_XoaThanhCong'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Assert_XoaThanhCongExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Xóa thành công.' label equals 'Xóa thành công.'
        /// </summary>
        public string UIXóathànhcôngTextName = "Xóa thành công.";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomeWindow : WinWindow
    {
        
        public UIHomeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Home";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public UIDgvBoPhanWindow UIDgvBoPhanWindow
        {
            get
            {
                if ((this.mUIDgvBoPhanWindow == null))
                {
                    this.mUIDgvBoPhanWindow = new UIDgvBoPhanWindow(this);
                }
                return this.mUIDgvBoPhanWindow;
            }
        }
        
        public UIREMOVEWindow UIREMOVEWindow
        {
            get
            {
                if ((this.mUIREMOVEWindow == null))
                {
                    this.mUIREMOVEWindow = new UIREMOVEWindow(this);
                }
                return this.mUIREMOVEWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDgvBoPhanWindow mUIDgvBoPhanWindow;
        
        private UIREMOVEWindow mUIREMOVEWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDgvBoPhanWindow : WinWindow
    {
        
        public UIDgvBoPhanWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dgvBoPhan";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        
        public UIRow1Row UIRow1Row
        {
            get
            {
                if ((this.mUIRow1Row == null))
                {
                    this.mUIRow1Row = new UIRow1Row(this);
                }
                return this.mUIRow1Row;
            }
        }
        
        public UIRow3Row UIRow3Row
        {
            get
            {
                if ((this.mUIRow3Row == null))
                {
                    this.mUIRow3Row = new UIRow3Row(this);
                }
                return this.mUIRow3Row;
            }
        }
        
        public UIRow0Row1 UIRow0Row1
        {
            get
            {
                if ((this.mUIRow0Row1 == null))
                {
                    this.mUIRow0Row1 = new UIRow0Row1(this);
                }
                return this.mUIRow0Row1;
            }
        }
        #endregion
        
        #region Fields
        private UIRow0Row mUIRow0Row;
        
        private UIRow1Row mUIRow1Row;
        
        private UIRow3Row mUIRow3Row;
        
        private UIRow0Row1 mUIRow0Row1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "BP04      ;Nhân Viên Bảo Vệ";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinCell UIBP04Cell
        {
            get
            {
                if ((this.mUIBP04Cell == null))
                {
                    this.mUIBP04Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIBP04Cell.SearchProperties[WinCell.PropertyNames.Value] = "BP04      ";
                    this.mUIBP04Cell.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUIBP04Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIBP04Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow1Row : WinRow
    {
        
        public UIRow1Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "BP02      ;Nhân Viên Kho Hàng";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinCell UIBP02Cell
        {
            get
            {
                if ((this.mUIBP02Cell == null))
                {
                    this.mUIBP02Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIBP02Cell.SearchProperties[WinCell.PropertyNames.Value] = "BP02      ";
                    this.mUIBP02Cell.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUIBP02Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIBP02Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow3Row : WinRow
    {
        
        public UIRow3Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "BP04      ;NVBV";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinCell UINVBVCell
        {
            get
            {
                if ((this.mUINVBVCell == null))
                {
                    this.mUINVBVCell = new WinCell(this);
                    #region Search Criteria
                    this.mUINVBVCell.SearchProperties[WinCell.PropertyNames.Value] = "NVBV";
                    this.mUINVBVCell.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUINVBVCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUINVBVCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow0Row1 : WinRow
    {
        
        public UIRow0Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "BP05      ;Nhân Viên Bảo Vệ";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinCell UIBP05Cell
        {
            get
            {
                if ((this.mUIBP05Cell == null))
                {
                    this.mUIBP05Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIBP05Cell.SearchProperties[WinCell.PropertyNames.Value] = "BP05      ";
                    this.mUIBP05Cell.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUIBP05Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIBP05Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIREMOVEWindow : WinWindow
    {
        
        public UIREMOVEWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "mnuxoa";
            this.WindowTitles.Add("Home");
            #endregion
        }
        
        #region Properties
        public WinButton UIREMOVEButton
        {
            get
            {
                if ((this.mUIREMOVEButton == null))
                {
                    this.mUIREMOVEButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIREMOVEButton.SearchProperties[WinButton.PropertyNames.Name] = "REMOVE";
                    this.mUIREMOVEButton.WindowTitles.Add("Home");
                    #endregion
                }
                return this.mUIREMOVEButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIREMOVEButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMessageBoxThanhCongWindow : WinWindow
    {
        
        public UIMessageBoxThanhCongWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MessageBoxThanhCong";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MessageBoxThanhCong");
            #endregion
        }
        
        #region Properties
        public UIXóathànhcôngWindow UIXóathànhcôngWindow
        {
            get
            {
                if ((this.mUIXóathànhcôngWindow == null))
                {
                    this.mUIXóathànhcôngWindow = new UIXóathànhcôngWindow(this);
                }
                return this.mUIXóathànhcôngWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIXóathànhcôngWindow mUIXóathànhcôngWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIXóathànhcôngWindow : WinWindow
    {
        
        public UIXóathànhcôngWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Test";
            this.WindowTitles.Add("MessageBoxThanhCong");
            #endregion
        }
        
        #region Properties
        public WinText UIXóathànhcôngText
        {
            get
            {
                if ((this.mUIXóathànhcôngText == null))
                {
                    this.mUIXóathànhcôngText = new WinText(this);
                    #region Search Criteria
                    this.mUIXóathànhcôngText.SearchProperties[WinText.PropertyNames.Name] = "Xóa thành công.";
                    this.mUIXóathànhcôngText.WindowTitles.Add("MessageBoxThanhCong");
                    #endregion
                }
                return this.mUIXóathànhcôngText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIXóathànhcôngText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMessageBoxCustomWindow : WinWindow
    {
        
        public UIMessageBoxCustomWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MessageBoxCustom";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MessageBoxCustom");
            #endregion
        }
        
        #region Properties
        public UIKhôngthểxóađượcWindow UIKhôngthểxóađượcWindow
        {
            get
            {
                if ((this.mUIKhôngthểxóađượcWindow == null))
                {
                    this.mUIKhôngthểxóađượcWindow = new UIKhôngthểxóađượcWindow(this);
                }
                return this.mUIKhôngthểxóađượcWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIKhôngthểxóađượcWindow mUIKhôngthểxóađượcWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIKhôngthểxóađượcWindow : WinWindow
    {
        
        public UIKhôngthểxóađượcWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Test";
            this.WindowTitles.Add("MessageBoxCustom");
            #endregion
        }
        
        #region Properties
        public WinText UIKhôngthểxóađượcText
        {
            get
            {
                if ((this.mUIKhôngthểxóađượcText == null))
                {
                    this.mUIKhôngthểxóađượcText = new WinText(this);
                    #region Search Criteria
                    this.mUIKhôngthểxóađượcText.SearchProperties[WinText.PropertyNames.Name] = "Không thể xóa được.";
                    this.mUIKhôngthểxóađượcText.WindowTitles.Add("MessageBoxCustom");
                    #endregion
                }
                return this.mUIKhôngthểxóađượcText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIKhôngthểxóađượcText;
        #endregion
    }
}
