//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThoiTrang.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6R47R7R\\SQLEXPRESS;Initial Catalog=QL_ShopThoiTrang;User ID=s" +
            "a;Password=sa2012")]
        public string QL_ShopThoiTrangConnectionString {
            get {
                return ((string)(this["QL_ShopThoiTrangConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6R47R7R\\SQLEXPRESS;Initial Catalog=QL_ShopThoiTrang;User ID=s" +
            "a;Password=sa2012")]
        public string ChuoiKetNoi {
            get {
                return ((string)(this["ChuoiKetNoi"]));
            }
            set {
                this["ChuoiKetNoi"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6R47R7R\\SQLEXPRESS;Initial Catalog=Clothesize;User ID=sa;Pass" +
            "word=sa2012")]
        public string ClothesizeConnectionString {
            get {
                return ((string)(this["ClothesizeConnectionString"]));
            }
        }
    }
}
